### PR TITLE
Improve cmake

### PR DESCRIPTION
**Pull request by agirault**
I am working at [Kitware](www.kitware.com), the creators and maintainers of [CMake](www.cmake.org), and I am working with some Falcons with VRPN for surgery simulation. Here is more on this pull-request:

### Summary
These commits takes better profit of CMake capabilities by using default CMake variables to better control binaries and libraries output path, which did not allow to use LibNiFalcon as an external project. They also favor LibUsb-1.0 as a default hid API.

### Context
When using LibNiFalcon as an external project / dependency of another project (see cmake [ExternalProject_Add](https://cmake.org/cmake/help/v3.0/module/ExternalProject.html)), compilation errors were occuring due to the variable `LIBRARY_OUTPUT_PATH` :

1) **Not on MSVC** : if variables were set to define the libraries  output dir ([`CMAKE_LIBRARY_OUTPUT_DIRECTORY`](https://cmake.org/cmake/help/v3.0/prop_tgt/LIBRARY_OUTPUT_DIRECTORY.html)) in the top level project, `LIBRARY_OUTPUT_PATH` would not keep track of those and would assume the libraries were built to the hardcoded location at `CMAKE_BINARY_DIR/lib` ([BuildSysCMakeLib.cmake:L65](https://github.com/libnifalcon/libnifalcon/pull/43/commits/dae3f31e055bbca5224ef83cdd666477d7c0709d#diff-8d2c8e9dfb367baa0e29d163d5a4c4cdL65)). When trying to link other libraries and executables to those first libraries, it would not find them since `TARGET_DIRECTORIES(LIBRARY_OUTPUT_PATH)` would not look at the correct location. The same issue applies with `CMAKE_RUNTIME_OUTPUT_DIRECTORY` and `EXECUTABLE_OUTPUT_PATH`, and results in errors at the LibNiFalcon level.

2) **On MSVC** : if variables were set to define the libraries output dir (`CMAKE_LIBRARY_OUTPUT_DIRECTORY_${config}`) those would be overwritten by the same `LIBRARY_OUTPUT_PATH` set and discussed above ([BuildSysCMakeLib.cmake:L123](https://github.com/libnifalcon/libnifalcon/pull/43/commits/dae3f31e055bbca5224ef83cdd666477d7c0709d#diff-8d2c8e9dfb367baa0e29d163d5a4c4cdL123)). This would result in errors at the top-project level.

### Proposed fixes
1) In the macro `INITIALIZE_BUILD()` of *BuildSysCMakeLib.cmake*, if those external project variables are not set, the default library output path is set to `CMAKE_BINARY_DIR/lib`, and the default runtime output path to `CMAKE_BINARY_DIR/bin`. If configurations are defined ([`CMAKE_CONFIGURATION_TYPES`](https://cmake.org/cmake/help/v3.0/variable/CMAKE_CONFIGURATION_TYPES.html), and not only `MSVC`), then the default output path will be `CMAKE_BINARY_DIR/lib/Config` (same with `/bin/`) automatically, helping to avoid mixing up libraries for different configurations.

2) The library output directories are appended to [`CMAKE_LIBRARY_PATH`](https://cmake.org/cmake/help/v3.0/variable/CMAKE_LIBRARY_PATH.html) in the same code hunk. This variable specifies the path that will be used by [`FIND_LIBRARY()`](https://cmake.org/cmake/help/v3.0/command/find_library.html) to check for the existence of libraries. This allows to get rid of `LINK_DIRECTORIES(${LIBRARY_OUTPUT_PATH})` in the whole project, since `TARGET_LINK_LIBRARIES()` will now be able to find any targets built into the path listed in `CMAKE_LIBRARY_PATH`.

3) Thanks to 2), there is no more need to define a library name to fit the platform (remove macro `CREATE_LIBRARY_LINK_NAME()`). Instead the target name can directly be given within the list of libraries to link against, like in *CMakeLists.txt* (`LIBNIFALCON_EXE_LINK_LIBS`), */src/util/CMakeLists.txt* (`CPP_LINK_LIBS`) or *examples/CMakeLists.txt* (`LIBNIFALCON_EXE_PO_LINK_LIBS`).

4) Since the target names actually include their library type, like `SHARED` or `STATIC`, doing `ADD_LIBRARY(name ALIAS name_type)` in the function `BUILDSYS_BUILD_LIB` (*BuildSysCMakeLib.cmake*) creates an alias name for the target that allows to directly give the library name in the list of libraries to link against, as explained in 3). This alias target can be used instead of the `*_DEPEND` target to define target dependencies, so we can get rid of those obsolete targets.

### CODE REVIEW

**Comment by qdot** [comment]
Wow, awesome, thanks for starting on this! If you want to assign Issue #41 to yourself, or just reference it in this bug, feel free. Looking forward to seeing what more canonical CMake should look like. :D

**Comment by agirault** [comment]
Hi @qdot. In this pull request I would like to offer a fix to be able to use LibNiFalcon as an external project easily, but I won't have the time to upgrade the whole CMake architecture. If I find the time to help upgrade to modern CMake (3.5), I'll create a new pull request instead. Would that work with you?

**Comment by agirault** [comment]
@qdot made some changes to simplify even more the CMake target creation, and work on #42 by making LibUsb-1.0 default for Windows and resolve what was needed around the issue.

I also put in a few fixes for bugs caused by obsolete boost objects and unsupported c++11 expressions on MSVC < 2015.

I updated the first comment of the pull request for you to see the big lines, for mode details I documented the rest in each commit messages.

Cheers! :tada:

**Comment by qdot** [comment]
Hmm. So I should hold off on merging this until we test the libusb stuff more then? Either that or if you want to isolate that commit out to its own pull request, I can bring in all the other work you've done while we check that out. I have a windows/mac/linux boxes here, but may not be able to test this myself for a day or two.

BTW, thanks again for the CMake improvements. I had a lot of opinions on CMake back when I first wrote this, and of course now haven't touched CMake for yaears (mostly been working in other languages that didn't need the build system or projects that had their own), so coming back to it I've been a bit confused at what I was thinking in the first place. :)

**Comment by agirault** [comment]
Pull request rebased to only include commits for CMake improvements and correcting the unsupported constexpr on MSVC.

I'll create a new pull request based on this once it is integrated for libusb1 support on windows.

Thank you!

**Pull request merged**
